---
# Template: 1.1.0
name: "Lint / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"
      - "develop"
      - "master"

jobs:
  lint-bash-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/devtmtf-lib"

      - name: "Build from source"
        run: "./bin/devtmtf-build"

      - name: "Run Bash linter"
        run: "./lib/testmansh -t -c build/testmantf"
...
